# Exported from Render on 2026-07-24T18:12:20Z
version: "1"
projects:
- name: brisk
  environments:
  - name: Production
    services:
    - type: web
      name: brisk
      runtime: node
      repo: https://github.com/athanasiosgkouvas/brisk
      plan: free
      envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_ENOKI_API_KEY
        sync: false
      - key: VITE_USDC_TYPE
        sync: false
      - key: VITE_SUI_NETWORK
        sync: false
      - key: VITE_WEB_REDIRECT_URI
        sync: false
      - key: VITE_BACKEND_URL
        sync: false
      - key: BRISK_GIFT_CARD_PKG
        sync: false
      - key: BRISK_RECORD_PKG
        sync: false
      - key: BRISK_PACKAGE_ID
        sync: false
      - key: BRISK_LOYALTY_FEE_BPS
        sync: false
      - key: BRISK_GIFT_CARD_FEE_BPS
        sync: false
      - key: BRISK_TREASURY_ADDRESS
        sync: false
      - key: BRISK_TILL_PKG
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        sync: false
      - key: SPONSORSHIP_DAILY_LIMIT_TX_COUNT
        sync: false
      - key: ENOKI_PRIVATE_KEY
        sync: false
      region: frankfurt
      buildCommand: cd ../webpay && npm install --include=dev && npm run build &&
        cd ../backend && npm install --include=dev && npm run build
      startCommand: npm start
      healthCheckPath: /health
      autoDeployTrigger: commit
      rootDir: backend
