import { randomBytes } from "node:crypto";

import { pool } from "../db.js";

// POS (ERP ↔ backend ↔ merchant phone) persistence. A merchant device registers
// a terminal (terminalId → owner/merchant/till binding + an auth token); the ERP
// initiates a sale that creates a session; the merchant device reports the
// on-chain settlement digest, which the ERP then polls for. Backed by Postgres
// (see db.ts) so state survives a socket reconnect or a backend redeploy.

export type PosSessionState = "PROCESSING" | "SUCCESS" | "FAILED" | "TIMEOUT" | "CANCELED";

export type PosTerminal = {
  terminalId: string;
  ownerAddr: string;
  merchantId: string;
  tillId: string;
  name: string;
  token: string;
  createdAt: string | null;
  lastSeenAt: string | null;
};

export type PosSession = {
  sessionId: string;
  terminalId: string;
  amountMicros: number;
  netCents: number;
  vatCents: number;
  totalCents: number;
  state: PosSessionState;
  aadeTransactionId: string | null;
  delivered: boolean;
  createdAt: string | null;
  updatedAt: string | null;
};

export type RegisterTerminalInput = {
  /** Stable per-device key (generated by the app). The short, human-typeable
   *  `terminalId` is assigned by the backend and stays bound to this device. */
  deviceId: string;
  ownerAddr: string;
  merchantId: string;
  tillId: string;
  name: string;
};

export type CreateSessionInput = {
  sessionId: string;
  terminalId: string;
  amountMicros: number;
  netCents: number;
  vatCents: number;
  totalCents: number;
};

function requirePool() {
  if (!pool) throw new Error("POS endpoints are unavailable (DATABASE_URL not configured)");
  return pool;
}

// ─── Terminals ───────────────────────────────────────────────────────────────

const TERMINAL_COLS = `terminal_id, owner_addr, merchant_id, till_id, name, token, created_at, last_seen_at`;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function rowToTerminal(r: any): PosTerminal {
  return {
    terminalId: r.terminal_id,
    ownerAddr: r.owner_addr,
    merchantId: r.merchant_id,
    tillId: r.till_id,
    name: r.name,
    token: r.token,
    createdAt: r.created_at ? new Date(r.created_at).toISOString() : null,
    lastSeenAt: r.last_seen_at ? new Date(r.last_seen_at).toISOString() : null,
  };
}

// Short, human-typeable terminal codes: uppercase, no ambiguous glyphs
// (0/O, 1/I/L) so a merchant can read one off a phone and key it into an
// in-store ERP by hand. 8 chars over a 31-symbol alphabet ≈ 8.5e11 combos.
const TERMINAL_CODE_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ";
const TERMINAL_CODE_LEN = 8;

function generateTerminalCode(): string {
  const bytes = randomBytes(TERMINAL_CODE_LEN);
  let out = "";
  for (let i = 0; i < TERMINAL_CODE_LEN; i++) {
    out += TERMINAL_CODE_ALPHABET[bytes[i] % TERMINAL_CODE_ALPHABET.length];
  }
  return out;
}

/** Normalize a terminal code as a merchant might type it into the ERP
 *  (lowercase, spaces/hyphens) into the canonical stored form. */
export function normalizeTerminalCode(raw: string): string {
  return raw.toUpperCase().replace(/[^0-9A-Z]/g, "");
}

async function getByDeviceId(deviceId: string): Promise<PosTerminal | null> {
  const db = requirePool();
  const { rows } = await db.query(
    `SELECT ${TERMINAL_COLS} FROM pos_terminals WHERE device_id = $1`,
    [deviceId],
  );
  return rows[0] ? rowToTerminal(rows[0]) : null;
}

/**
 * Register (or re-register) a terminal for a device, returning its short code +
 * auth token. Bound to `deviceId`: the same device always maps to the same
 * terminal code (and token) across re-registrations, so changing the till/name
 * updates that row rather than minting a new code. A fresh device gets a unique
 * code (retried on the rare collision).
 */
export async function registerTerminal(input: RegisterTerminalInput): Promise<PosTerminal> {
  const db = requirePool();
  for (let attempt = 0; attempt < 5; attempt++) {
    // Reuse this device's existing terminal if it has one.
    const existing = await getByDeviceId(input.deviceId);
    if (existing) {
      const { rows } = await db.query(
        `UPDATE pos_terminals
            SET owner_addr = $2, merchant_id = $3, till_id = $4, name = $5, last_seen_at = now()
          WHERE terminal_id = $1
        RETURNING ${TERMINAL_COLS}`,
        [existing.terminalId, input.ownerAddr, input.merchantId, input.tillId, input.name],
      );
      return rowToTerminal(rows[0]);
    }
    // New device → mint a unique short code.
    const code = generateTerminalCode();
    const token = randomBytes(24).toString("hex");
    try {
      const { rows } = await db.query(
        `INSERT INTO pos_terminals
           (terminal_id, device_id, owner_addr, merchant_id, till_id, name, token, last_seen_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, now())
         RETURNING ${TERMINAL_COLS}`,
        [code, input.deviceId, input.ownerAddr, input.merchantId, input.tillId, input.name, token],
      );
      return rowToTerminal(rows[0]);
    } catch (err: unknown) {
      // 23505 = unique_violation on terminal_id (code clash) OR device_id (a
      // concurrent register for this device) — retry; the loop re-checks device.
      if ((err as { code?: string })?.code === "23505") continue;
      throw err;
    }
  }
  throw new Error("Failed to allocate a unique terminal code");
}

export async function getTerminal(terminalId: string): Promise<PosTerminal | null> {
  const db = requirePool();
  const { rows } = await db.query(
    `SELECT ${TERMINAL_COLS} FROM pos_terminals WHERE terminal_id = $1`,
    [terminalId],
  );
  return rows[0] ? rowToTerminal(rows[0]) : null;
}

/** Touch last_seen_at when a terminal connects its socket. */
export async function touchTerminal(terminalId: string): Promise<void> {
  const db = requirePool();
  await db.query(`UPDATE pos_terminals SET last_seen_at = now() WHERE terminal_id = $1`, [
    terminalId,
  ]);
}

// ─── Sessions ──────────────────────────────────────────────────────────────

const SESSION_COLS = `session_id, terminal_id, amount_micros, net_cents, vat_cents, total_cents,
            state, aade_transaction_id, delivered, created_at, updated_at`;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function rowToSession(r: any): PosSession {
  return {
    sessionId: r.session_id,
    terminalId: r.terminal_id,
    amountMicros: Number(r.amount_micros),
    netCents: Number(r.net_cents),
    vatCents: Number(r.vat_cents),
    totalCents: Number(r.total_cents),
    state: r.state,
    aadeTransactionId: r.aade_transaction_id ?? null,
    delivered: r.delivered,
    createdAt: r.created_at ? new Date(r.created_at).toISOString() : null,
    updatedAt: r.updated_at ? new Date(r.updated_at).toISOString() : null,
  };
}

/**
 * Create a session for a sale. Idempotent on sessionId (an ERP retry with the
 * same id returns the existing row rather than resetting state/delivery).
 */
export async function createSession(input: CreateSessionInput): Promise<PosSession> {
  const db = requirePool();
  const { rows } = await db.query(
    `INSERT INTO pos_sessions (session_id, terminal_id, amount_micros, net_cents, vat_cents, total_cents)
       VALUES ($1, $2, $3, $4, $5, $6)
     ON CONFLICT (session_id) DO UPDATE SET session_id = pos_sessions.session_id
     RETURNING ${SESSION_COLS}`,
    [
      input.sessionId,
      input.terminalId,
      input.amountMicros,
      input.netCents,
      input.vatCents,
      input.totalCents,
    ],
  );
  return rowToSession(rows[0]);
}

export async function getSession(sessionId: string): Promise<PosSession | null> {
  const db = requirePool();
  const { rows } = await db.query(
    `SELECT ${SESSION_COLS} FROM pos_sessions WHERE session_id = $1`,
    [sessionId],
  );
  return rows[0] ? rowToSession(rows[0]) : null;
}

/**
 * Lazily time out a session left PROCESSING past its TTL — the backstop for a
 * sale the device never resolved (app killed mid-queue, terminal never picked it
 * up). Called before a poll so the ERP gets a terminal answer instead of polling
 * forever. Idempotent; no-op unless the row is still PROCESSING and stale.
 */
export async function expireStaleSession(sessionId: string, ttlSec: number): Promise<void> {
  const db = requirePool();
  await db.query(
    `UPDATE pos_sessions SET state = 'TIMEOUT', updated_at = now()
      WHERE session_id = $1 AND state = 'PROCESSING'
        AND created_at < now() - ($2 || ' seconds')::interval`,
    [sessionId, String(ttlSec)],
  );
}

/** Mark a session settled with its on-chain digest (idempotent; only flips a
 *  still-PROCESSING row). */
export async function markSuccess(sessionId: string, digest: string): Promise<boolean> {
  const db = requirePool();
  const { rowCount } = await db.query(
    `UPDATE pos_sessions
        SET state = 'SUCCESS', aade_transaction_id = $2, updated_at = now()
      WHERE session_id = $1 AND state = 'PROCESSING'`,
    [sessionId, digest],
  );
  return (rowCount ?? 0) > 0;
}

/** Mark a session to a non-success terminal state (idempotent; only flips a
 *  still-PROCESSING row). CANCELED = the merchant cancelled on the device. */
export async function markFailed(
  sessionId: string,
  state: "FAILED" | "TIMEOUT" | "CANCELED",
): Promise<boolean> {
  const db = requirePool();
  const { rowCount } = await db.query(
    `UPDATE pos_sessions
        SET state = $2, updated_at = now()
      WHERE session_id = $1 AND state = 'PROCESSING'`,
    [sessionId, state],
  );
  return (rowCount ?? 0) > 0;
}

/**
 * Mark a session as delivered — set ONLY when the device ACKs receipt of the
 * SALE over the socket (not optimistically on send), so a push that never
 * reaches a half-open socket leaves the session undelivered and it is re-pushed
 * on the next connect. Idempotent.
 */
export async function markDelivered(sessionId: string): Promise<void> {
  const db = requirePool();
  await db.query(`UPDATE pos_sessions SET delivered = true WHERE session_id = $1`, [sessionId]);
}

/**
 * Not-yet-delivered PROCESSING sessions for a terminal (oldest first) — pushed to
 * the device on (re)connect so sales that arrived while the socket was down are
 * redelivered. This is a pure read: `delivered` flips only on the device's ACK,
 * so an un-ACKed session keeps being re-pushed until the device confirms it.
 */
export async function getUndeliveredSessions(
  terminalId: string,
  ttlSec: number,
): Promise<PosSession[]> {
  const db = requirePool();
  // Skip sessions older than the TTL — an ancient un-ACked sale is stale, not
  // something to charge on reconnect (a poll will time it out).
  const { rows } = await db.query(
    `SELECT ${SESSION_COLS} FROM pos_sessions
       WHERE terminal_id = $1 AND state = 'PROCESSING' AND delivered = false
         AND created_at > now() - ($2 || ' seconds')::interval
       ORDER BY created_at ASC`,
    [terminalId, String(ttlSec)],
  );
  return rows.map(rowToSession);
}
